- fixed compilation with Clang and GCC
src/gl/scene/gl_flats.cpp:215:3: error: cannot jump from this goto statement to its label
src/r_data/models/models.cpp:100:18: error: no member named 'floor' in namespace 'std'

# Conflicts:
#	src/gl/scene/gl_flats.cpp